name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npx playwright install chromium
      
      - name: Run tests (unit)
        env:
          OPENAI_API_KEY: dummy
          FAST_MODE: '1'
        run: |
          pytest -q -k "not e2e"

      - name: Run tests (e2e)
        env:
          OPENAI_API_KEY: dummy
          FAST_MODE: '1'
        run: |
          pytest -q -m e2e


